// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARnAoFJHB5mgGsH2-SJ4ERKVEO4DAed8E',
    appId: '1:433276855579:web:14ee4d4cea073462ffdfbe',
    messagingSenderId: '433276855579',
    projectId: 'firstproject-6de6c',
    authDomain: 'firstproject-6de6c.firebaseapp.com',
    storageBucket: 'firstproject-6de6c.appspot.com',
    measurementId: 'G-89NYVHKN5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg5WG2J2QiVGOkRhdjBgdoUQZ7sGPqPVw',
    appId: '1:433276855579:android:bbde0bc49ec1815affdfbe',
    messagingSenderId: '433276855579',
    projectId: 'firstproject-6de6c',
    storageBucket: 'firstproject-6de6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1LDU7pZBdPpjowNMVMQGiraSqSpK0v0M',
    appId: '1:433276855579:ios:159494f5e0155496ffdfbe',
    messagingSenderId: '433276855579',
    projectId: 'firstproject-6de6c',
    storageBucket: 'firstproject-6de6c.appspot.com',
    iosBundleId: 'com.example.firstproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1LDU7pZBdPpjowNMVMQGiraSqSpK0v0M',
    appId: '1:433276855579:ios:4494e9af280adc76ffdfbe',
    messagingSenderId: '433276855579',
    projectId: 'firstproject-6de6c',
    storageBucket: 'firstproject-6de6c.appspot.com',
    iosBundleId: 'com.example.firstproject.RunnerTests',
  );
}
